### ISSUE TITLE
[FR] Not jumping to the end of the page on the last heading

### ISSUE THREAD

**Issue by Archie-2021** [LifeFi/obsidian-jump#1]
Hi,

Very glad to find this pluging yesterday, I really needed such a thing, I was using Code Editor hotkeys pluig to navigate between heading and it was not as good as this one.

I think having a setting to change mode can be useful. One very annoying thing is that if I go to the last item (lets say I am jumping between level 2 heading in document) and I hit the last one it put me to the end of document and there is no way to go back. So adding a type of memory and using that on an empty line would be nice. Also not jumping to the end of document if it is the last one is a good option in itself.

I have some other suggestions too, let me know if you are interersted. I can make separate thread for each one but since it is a new plugin and there is not that many threads open I though putting all in one thread is OK.

Thanks you for this simple but super useful plugin

**Comment by sangwon-j** [comment]
Hi, 

Thank you sincerely for your feedback.

I have added the functionality to the Settings to 'Include first/last line' and 'Threshold' options.
Please check update ver 0.1.8.

Thanks

**Comment by sangwon-j** [comment]
I'm closing the issue as incorporated it into the 0.1.8 build release.
