### ISSUE TITLE
Add an option for separate modes for headings and bullet points

### ISSUE THREAD

**Issue by Archie-2021** [LifeFi/obsidian-jump#2]
Hey, and sorry for replying later to you last post on previous thread. I really appreciate the new features you added, I think i missed this suggestion:

Navigating between headings and bullet points/tasks is a totally different area, right now if I am on a heading level 1 and want to jump a little bit lower using "lower level" option will drop me to a bullet point if it is the next line after this level one heading, I think there is a need to:
- Have a separate mode to select between bullet points and headers.
- Perfectly Have a command for this toggle in command pallet so that switching is easy.

Thanks again

**Comment by sangwon-j** [comment]
Thank you for your feedback. I completely agree with your points.

When the cursor is on a heading, it should be able to move levels only within the heading. Similarly, when the cursor is on a list, it should be able to move levels only within the list.

I considered whether mode switching would be necessary, but it seems too complex, so I think it would be better not to include it for now.

We will incorporate your suggestions into version 0.1.9.

Thank you very much for your interest.

**Comment by sangwon-j** [comment]
I'm closing the issue as incorporated it into the 0.1.9 build release.

**Comment by Archie-2021** [comment]
Thank you very much
